services:
  web:
    image: caddy:latest
    restart: 'always'
    container_name: invoiceninja_web
    depends_on:
      - app
      - phpmyadmin
    env_file: .env
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './Caddyfile:/etc/caddy/Caddyfile'
      - '$INVOICE_NINJA_HOME/public:/var/www/app/public:ro'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:5
    restart: 'always'
    container_name: invoiceninja_app
    depends_on:
      - db
    hostname: in5
    env_file: .env
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '$INVOICE_NINJA_HOME/public:/var/www/app/public'
      - '$INVOICE_NINJA_HOME/storage:/var/www/app/storage'
    networks:
      - invoiceninja

  db:
    image: mysql:8
    restart: 'always'
    container_name: 'invoiceninja_db'
    env_file: .env
    volumes:
      - '$INVOICE_NINJA_HOME/db:/var/lib/mysql'
    networks:
      - invoiceninja

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    container_name: 'invoiceninja_dbadmin'
    env_file: .env
    networks:
      - invoiceninja
    environment:
      PMA_HOST: '$DB_HOST'
      PMA_PORT: 3306

networks:
  invoiceninja:
